package net.Andrewcpu.UTILS.Commands.utils;

/**
 * Created by andrewpstein on 8/12/15.
 */
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.lang.WordUtils;

public enum ItemWordNames {

//Made by LCastr0
//sbuttercraft.com
//Please, do not remove this lines!

 ACACIA_STAIRS("acaciawoodstairs"),
ACTIVATOR_RAIL("activatorrail"),
AIR("air"),
ANVIL("anvil"),
APPLE("apple"),
ARROW("arrow"),
BAKED_POTATO("bakedpotato"),
BEACON("beacon"),
BED("bed"),
BED_BLOCK("bedblock"),
BEDROCK("bedrock"),
BIRCH_WOOD_STAIRS("birchwoodstairs"),
BLAZE_POWDER("blazepowder"),
BLAZE_ROD("blazerod"),
BOAT("boat"),
BONE("bone"),
BOOK("book"),
BOOK_AND_QUILL("bookandquill"),
BOOKSHELF("bookshelf"),
BOW("bow"),
BOWL("bowl"),
BREAD("bread"),
BREWING_STAND("brewingstand"),
BRICK("bricks"),
BRICK_STAIRS("brickstairs"),
BROWN_MUSHROOM("brownmushroom"),
BUCKET("bucket"),
BURNING_FURNACE("burningfurnace"),
CACTUS("cactus"),
CAKE("cake"),
CAKE_BLOCK("cake"),
CARPET("carpet"),
CARROT("carrot"),
CARROT_ITEM("carrot"),
CARROT_STICK("carrotonastick"),
CAULDRON("cauldron"),
CAULDRON_ITEM("cauldron"),
CHAINMAIL_BOOTS("chainmailboots"),
CHAINMAIL_CHESTPLATE("chainmailchestplate"),
CHAINMAIL_HELMET("chainmailhelmet"),
CHAINMAIL_LEGGINGS("chainmailleggings"),
CHEST("chest"),
CLAY("clay"),
CLAY_BALL("clay"),
CLAY_BRICK("brick"),
COAL("coal"),
COAL_BLOCK("blockofcoal"),
COAL_ORE("coalore"),
COBBLE_WALL("cobblestonewall"),
COBBLESTONE("cobblestone"),
COBBLESTONE_STAIRS("cobblestonestairs"),
COCOA("cocoa"),
COMMAND("commandblock"),
COMPASS("compass"),
COOKED_BEEF("steak"),
COOKED_CHICKEN("cookedchicken"),
COOKED_FISH("cookedfish"),
COOKIE("cookie"),
CROPS("crops"),
DARK_OAK_STAIRS("darkoakwoodstairs"),
DAYLIGHT_DETECTOR("daylightsensor"),
DEAD_BUSH("deadbush"),
DETECTOR_RAIL("detectorrail"),
DIAMOND("diamond"),
DIAMOND_AXE("diamondaxe"),
DIAMOND_BARDING("diamondhorsearmor"),
DIAMOND_BLOCK("diamondblock"),
DIAMOND_BOOTS("diamondboots"),
DIAMOND_CHESTPLATE("diamondchestplate"),
DIAMOND_HELMET("diamondhelmet"),
DIAMOND_HOE("diamondhoe"),
DIAMOND_LEGGINGS("diamondleggings"),
DIAMOND_ORE("diamondore"),
DIAMOND_PICKAXE("diamondpickaxe"),
DIAMOND_SPADE("diamondshovel"),
DIAMOND_SWORD("diamondsword"),
DIODE("redstonerepeater"),
DIODE_BLOCK_OFF("redstonerepeater"),
DIODE_BLOCK_ON("redstonerepeater"),
DIRT("dirt"),
DISPENSER("dispenser"),
DOULBE_PLANT("doubleplant"),
DOUBLE_STEP("doubleslab"),
DRAGON_EGG("dragonegg"),
DROPPER("dropper"),
EGG("egg"),
EMERALD("emerald"),
EMERALD_BLOCK("emeraldblock"),
EMERALD_ORE("emeraldore"),
EMPTY_MAP("emptymap"),
ENCHANTED_BOOK("enchantedbook"),
ENCHANTMENT_TABLE("enchantmenttable"),
ENDER_CHEST("enderchest"),
ENDER_PEARL("enderpearl"),
ENDER_PORTAL("enderportal"),
ENDER_PORTAL_FRAME("enderprotalframe"),
ENDER_STONE("enderstone"),
EXP_BOTTLE("bottleo'enchanting"),
EXPLOSIVE_MINECART("minecartwithtnt"),
EYE_OF_ENDER("eyeofender"),
FEATHER("feather"),
FENCE("fence"),
FENCE_GATE("fencegate"),
FERMENTED_SPIDER_EYE("fermentedspidereye"),
FIRE("fire"),
FIREBALL("fireball"),
FIREWORK("firework"),
FIREWORK_CHARGE("fireworkcharge"),
FISHING_ROD("fishingrod"),
FLINT("flint"),
FLINT_AND_STEEL("flintandsteel"),
FLOWER_POT("flowerpot"),
FLOWER_POT_ITEM("flowerpot"),
FURNACE("furnace"),
GHAST_TEAR("ghasttear"),
GLASS("glass"),
GLASS_BOTTLE("glassbottle"),
GLOWING_REDSTONE_ORE("redstoneore"),
GLOWSTONE("glowstone"),
GLOWSTONE_DUST("glowstonedust"),
GOLD_AXE("goldaxe"),
GOLD_BARDING("goldhorsearmor"),
GOLD_BLOCK("goldblock"),
GOLD_BOOTS("goldboots"),
GOLD_CHESTPLATE("goldchestplate"),
GOLD_HELMET("goldhelmet"),
GOLD_HOE("goldhoe"),
GOLD_INGOT("goldingot"),
GOLD_LEGGINGS("goldleggings"),
GOLD_NUGGET("goldnugget"),
GOLD_ORE("goldore"),
GOLD_PICKAXE("goldpickaxe"),
GOLD_PLATE("weightedpressureplate"),
GOLD_RECORD("musicdisc-13"),
GOLD_SPADE("goldshovel"),
GOLD_SWORD("goldsword"),
GOLDEN_APPLE("goldenapple"),
GOLDEN_CARROT("goldencarrot"),
GRASS("grass"),
GRAVEL("gravel"),
GREEN_RECORD("musicdisc-cat"),
GRILLED_PORK("cookedporkchop"),
HARD_CLAY("hardenedclay"),
HAY_BLOCK("haybale"),
HOPPER("hopper"),
HOPPER_MINECART("minecartwithhopper"),
HUGE_MUSHROOM_1("hugemushroom"),
HUGE_MUSHROOM_2("hugemushroom"),
ICE("ice"),
INK_SACK("inksack"),
IRON_AXE("ironaxe"),
IRON_BARDING("ironhorsearmor"),
IRON_BLOCK("ironblock"),
IRON_BOOTS("ironboots"),
IRON_CHESTPLATE("ironchestplate"),
IRON_DOOR("irondoor"),
IRON_DOOR_BLOCK("irondoorblock"),
IRON_FENCE("ironfence"),
IRON_HELMET("ironhelmet"),
IRON_HOE("ironhoe"),
IRON_INGOT("ironingot"),
IRON_LEGGINGS("ironleggings"),
IRON_ORE("ironore"),
IRON_PICKAXE("ironpickaxe"),
IRON_PLATE("weightedpressureplate"),
IRON_SPADE("ironshovel"),
IRON_SWORD("ironsword"),
ITEM_FRAME("itemframe"),
JACK_O_LANTERN("jack-o-lantern"),
JUKEBOX("jukebox"),
JUNGLE_WOOD_STAIRS("junglewoodstairs"),
LADDER("ladder"),
LAPIS_BLOCK("lapislazuliblock"),
LAPIS_ORE("lapislazuliore"),
LAVA("lava"),
LAVA_BUCKET("lavabucket"),
LEASH("lead"),
LEATHER("leather"),
LEATHER_BOOTS("leatherboots"),
LEATHER_CHESTPLATE("leathertunic"),
LEATHER_HELMET("leathercap"),
LEATHER_LEGGINGS("leatherpants"),
LEAVES("leaves"),
LEAVES_2("leaves"),
LEVER("lever"),
LOCKED_CHEST("lockedchest"),
LOG("woodlog"),
LOG_1("woodlog"),
LONG_GRASS("shrub"),
MAGMA_CREAM("magmacream"),
MAP("map"),
MELON("melon"),
MELON_BLOCK("melon"),
MELON_SEEDS("melonseeds"),
MELON_STEM("melonstem"),
MILK_BUCKET("milkbucket"),
MINECART("minecart"),
MOB_SPAWNER("mobspawner"),
MONSTER_EGG("mobegg"),
MONSTER_EGGS("silverfishblock"),
MOSSY_COBBLESTONE("mossycobblestone"),
MUSHROOM_SOUP("mushroomsoup"),
MYCEL("mycelium"),
NAME_TAG("nametag"),
NETHER_BRICK("netherbrick"),
NETHER_BRICK_ITEM("netherbrick"),
NETHER_BRICK_STAIRS("netherbrickstairs"),
NETHER_FENCE("netherbrickfence"),
NETHER_STALK("netherwart"),
NETHER_STAR("netherstar"),
NETHER_WARTS("netherwart"),
NETHERRACK("netherrack"),
NOTE_BLOCK("noteblock"),
OBSIDIAN("obsidian"),
PAINTING("painting"),
PAPER("paper"),
PISTON_BASE("piston"),
PISTON_EXTENSION("pistonextension"),
PISTON_MOVING_PIECE("movingpiston"),
PISTON_STICK_BASE("stickypiston"),
POISONOUS_POTATO("poisonouspotato"),
PORK("rawporkchop"),
PORTAL("portal"),
POTATO("potato"),
POTATO_ITEM("potato"),
POTION("potion"),
POWERED_MINECART("minecartwithfurnace"),
POWERED_RAIL("poweredrail"),
PUMPKIN("pumpkin"),
PUMPKIN_PIE("pumpkinpie"),
PUMPKIN_SEEDS("pumpkinseeds"),
PUMPKIN_STEM("pumpkinstem"),
QUARTZ("quartz"),
QUARTZ_BLOCK("blockofquartz"),
QUARTZ_ORE("quartzore"),
QUARTZ_STAIRS("quartzstairs"),
RAILS("rail"),
RAW_BEEF("rawbeef"),
RAW_CHICKEN("rawchicken"),
RAW_FISH("rawfish"),
RECORD_10("musicdisc-ward"),
RECORD_11("musicdisc-11"),
RECORD_12("musicdisc-wait"),
RECORD_3("musicdisc-blocks"),
RECORD_4("musicdisc-chirp"),
RECORD_5("musicdisc-far"),
RECORD_6("musicdisc-mall"),
RECORD_7("musicdisc-mellohi"),
RECORD_8("mucisdisc-stal"),
RECORD_9("musicdisc-strad"),
RED_MUSHROOM("redmushroom"),
RED_ROSE("redrose"),
REDSTONE("redstone"),
REDSTONE_BLOCK("blockofredstone"),
REDSTONE_COMPARATOR("redstonecomparator"),
REDSTONE_COMPARATOR_OFF("redstonecomparator"),
REDSTONE_COMPARATOR_ON("redstonecomparator"),
REDSTONE_LAMP_OFF("redstonelamp"),
REDSTONE_LAMP_ON("redstonelamp"),
REDSTONE_ORE("redstoneore"),
REDSTONE_TORCH_OFF("redstonetorch"),
REDSTONE_TORCH_ON("redstonetorch"),
REDSTONE_WIRE("redstone"),
ROTTEN_FLESH("rottenflesh"),
SADDLE("saddle"),
SAND("sand"),
SANDSTONE("sandstone"),
SANDSTONE_STAIRS("sandstonestairs"),
SAPLING("sapling"),
SEEDS("seeds"),
SHEARS("shears"),
SIGN("sign"),
SIGN_POST("sign"),
SKULL("skull"),
SKULL_ITEM("skull"),
SLIME_BLOCK("slimeblock"),
SMOOTH_BRICK("stonebricks"),
SMOOTH_STAIRS("stonebricksstairs"),
SNOW("snow"),
SNOW_BALL("snowball"),
SNOW_BLOCK("snowblock"),
SOIL("farmland"),
SOUL_SAND("soulsand"),
SPECKLED_MELON("glisteringmelon"),
SPIDER_EYE("spidereye"),
SPONGE("sponge"),
SPRUCE_WOOD_STAIRS("sprucewoodstairs"),
STAINED_CLAY("stainedclay"),
STAINED_GLASS("stainedglass"),
STAINED_GLASS_PANE("stainedglasspane"),
STATIONARY_LAVA("stationarylava"),
STEP("slab"),
STICK("stick"),
STONE("stone"),
STONE_AXE("stoneaxe"),
STONE_BUTTON("button"),
STONE_HOE("stonehoe"),
STONE_PICKAXE("stonepickaxe"),
STONE_PLATE("pressureplate"),
STONE_SPADE("stoneshovel"),
STONE_SWORD("stonesword"),
STORAGE_MINECART("minecartwithchest"),
STRING("string"),
SUGAR("sugar"),
SUGAR_CANE("sugarcane"),
SUGAR_CANE_BLOCK("sugarcane"),
SULPHUR("gunpowder"),
THIN_GLASS("glasspane"),
TNT("tnt"),
TORCH("torch"),
TRAP_DOOR("trapdoor"),
TRAPPED_CHEST("trappedchest"),
TRIPWIRE("tripwire"),
TRIPWIRE_HOOK("tripwirehook"),
VINE("vines"),
WALL_SIGN("sign"),
WATCH("clock"),
WATER("water"),
WATER_BUCKET("waterbucket"),
WATER_LILY("lilypad"),
WEB("cobweb"),
WHEAT("wheat"),
WOOD("wood"),
WOOD_AXE("woodenaxe"),
WOOD_BUTTON("button"),
WOOD_DOOR("woodendoor"),
WOOD_DOUBLE_STEP("doublewoodslab"),
WOOD_HOE("woodenhoe"),
WOOD_PICKAXE("woodenpickaxe"),
WOOD_PLATE("pressureplate"),
WOOD_SPADE("woodenshovel"),
WOOD_STAIRS("woodstairs"),
WOOD_STEP("woodslab"),
WOOD_SWORD("woodensword"),
WOODEN_DOOR("woodendoor"),
WOOL("wool"),
WORKBENCH("craftingtable"),
WRITTEN_BOOK("writtenbook"),
YELLOW_FLOWER("dandelion")
;

    private final String name;

    private ItemWordNames(final String name){
        this.name = name;
    }

    public String toString(){
        return name;
    }

    private static final Map<String, ItemWordNames> lookup = new HashMap<String, ItemWordNames>();
    //Returns the Material name from the given block name
    public static String getMaterialName(String fromBlockName){
        for(ItemWordNames n : values()){
            lookup.put(n.toString(), n);
        }
        String result = lookup.get(fromBlockName).name();
        return result;
    }

    //Returns the item name with the first letter uppercased (Example: pressure plate -> Pressure plate)
    public String firstUpperCased(){
        char first = Character.toUpperCase(name.charAt(0));
        return first + name.substring(1);
    }

    //Returns the item name with all the words with the first letter uppercased (Example: pressure plate -> Pressure Plate)
    public String firstAllUpperCased(){
        return WordUtils.capitalizeFully(name);
    }

    //Returns the item name with all the letters uppercased (Example: pressure plate -> PRESSURE PLATE)
    public String allUpperCased(){
        return name.toUpperCase();
    }

}
